source "https://supermarket.chef.io"

cookbook 'ntp'
cookbook 'graphite',       :github => 'hw-cookbooks/graphite'
cookbook 'collectd',       :github => 'coderanger/chef-collectd'
cookbook 'statsd',         :github => 'hectcastro/chef-statsd'
cookbook 'rvm',            :github => 'fnichol/chef-rvm'
cookbook 'user',           :github => 'fnichol/chef-user'
cookbook 'timezone_lwrp',  :github => 'dragonsmith/chef-timezone'
cookbook 'logrotate',      :github => 'opscode-cookbooks/logrotate'
cookbook 'nginx',          :github => 'miketheman/nginx'
cookbook 'memcached',      :github => 'opscode-cookbooks/memcached'
cookbook 'redis',          :github => 'miah/chef-redis'
cookbook 'postgresql',     :github => 'hw-cookbooks/postgresql'

cookbook 'base',              :path => 'site-cookbooks/base'
cookbook 'hosts',             :path => 'site-cookbooks/hosts'
cookbook 'collectd_graphite', :path => 'site-cookbooks/collectd_graphite'
cookbook 'graphite_all',      :path => 'site-cookbooks/graphite_all'
cookbook 'ruby',              :path => 'site-cookbooks/ruby'
cookbook 'apache_auth',       :path => 'site-cookbooks/apache_auth'
cookbook 'iptables',          :path => 'site-cookbooks/iptables'
cookbook 'time',              :path => 'site-cookbooks/time'
cookbook 'tmate',             :path => 'site-cookbooks/tmate'
cookbook 'tmate_nginx',       :path => 'site-cookbooks/tmate_nginx'
cookbook 'tmate_master',      :path => 'site-cookbooks/tmate_master'
cookbook 'tmate_proxy',       :path => 'site-cookbooks/tmate_proxy'
